platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :generate_multiple_pod_projects => true

target 'WalletConnect_Example' do
  pod 'WalletConnect', :path => '../'
  pod 'TrustWalletCore', '0.12.25'
  target 'WalletConnect_Tests' do
    inherit! :search_paths
  end
end

